ollama:
  ollama:
    gpu:
      enabled: true
    models:
      pull:
        - "qwen2.5-coder:7b-instruct"
  extraEnv:
    - name: OLLAMA_CONTEXT_LENGTH
      value: "8192"
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway-internal
        namespace: kube-system
    hostnames:
      - ollama.nwallace.io
  nodeSelector:
    kubernetes.io/hostname: arch-desktop