ollama:
  ollama:
    gpu:
      enabled: true
    models:
      create:
        - name: "qwen3-coder"
          template: |
            FROM qwen3.5:9b-q4_k_m
            PARAMETER num_ctx 131072
      run:
        - "qwen3-coder"
  httpRoute:
    enabled: true
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-internal
      namespace: kube-system
    hostnames:
    - ollama.nwallace.io
  nodeSelector:
    kubernetes.io/hostname: arch-desktop
  persistentVolume:
    enabled: true
    existingClaim: ollama-data
  image:
    repository: harbor.nwallace.io/docker-hub/ollama/ollama
