node-feature-discovery:
  image:
    repository: harbor.nwallace.io/k8s/nfd/node-feature-discovery
  prometheus:
    labels:
      backstage.io/kubernetes-id: metrics-server
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"