{{- $aigwSigningKeySecret := include "ai-gateway.aigwSigningKey.secret" . -}}
{{- $aigwValidationKeySecret := include "ai-gateway.aigwValidationKey.secret" . -}}
{{- $duoWorkflowSigningKeySecret := include "ai-gateway.duoWorkflowSigningKey.secret" . -}}
{{- $duoWorkflowValidationKeySecret := include "ai-gateway.duoWorkflowValidationKey.secret" . -}}

{{- if or (not $aigwSigningKeySecret) (not $aigwValidationKeySecret) (not $duoWorkflowSigningKeySecret) (not $duoWorkflowValidationKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-gateway.fullname" . }}-jwt-keys
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not $aigwSigningKeySecret }}
  aigwSigningKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
  {{- if not $aigwValidationKeySecret }}
  aigwValidationKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
  {{- if not $duoWorkflowSigningKeySecret }}
  duoWorkflowSigningKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
  {{- if not $duoWorkflowValidationKeySecret }}
  duoWorkflowValidationKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
{{- end }}
