{{- $anthropicApiKeyValue := (.Values.anthropicApiKey).value -}}
{{- $vertexTextModelJsonKeyValue := ((.Values.vertexTextModel).jsonKey).value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-gateway.fullname" . }}
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
data:
  {{- if $anthropicApiKeyValue }}
  ANTHROPIC_API_KEY: {{ $anthropicApiKeyValue | b64enc | quote }}
  {{- end }}
  {{- if $vertexTextModelJsonKeyValue }}
  AIGW_VERTEX_TEXT_MODEL__JSON_KEY: {{ $vertexTextModelJsonKeyValue | b64enc | quote }}
  {{- end }}
type: Opaque
