apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argo-cd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: home-server
  source:
    path: charts/vaultwarden
    repoURL: https://gitlab.nwallace.io/home-server/home-server-helm.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      name: vaultwarden
      jsonPointers:
        - /spec/plugins/0/enabled
        - /spec/plugins/0/isWALArchiver
        - /spec/externalClusters/0/plugin/enabled
        - /spec/externalClusters/0/plugin/isWALArchiver