apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data
spec:
  capacity:
    storage: 30Gi
  hostPath:
    path: /var/lib/longhorn/ollama
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ollama-data
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arch-desktop
