apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  resources:
    limits:
        memory: "500Mi"
  instances: 3
  switchoverDelay: 60
  smartShutdownTimeout: 120
  stopDelay: 60
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  inheritedMetadata:
    labels:
      {{- include "commonLabels" . | nindent 6 }}
  affinity:
    podAntiAffinityType: required
    nodeSelector:
      storage: 'true'
  imageName: {{ .Values.dbImage }}
  imagePullPolicy: Always
  bootstrap:
    # initdb:
    #   database: registry
    #   owner: harbor
    #   secret:
    #     name: harbor-postgresql-password
    recovery:
      source: {{ .Release.Name }}
      database: harbor
      owner: harbor
      secret:
        name: {{ .Release.Name }}-postgresql-password
  managed:
    roles:
    - name: harbor
      connectionLimit: -1
      inherit: true
      ensure: present
      login: true
      passwordSecret:
        name: {{ .Release.Name }}-postgresql-password
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
      storageClassName: longhorn-db
      volumeMode: Filesystem
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: longhorn-db
      volumeMode: Filesystem
  postgresql:
    parameters:
      max_slot_wal_keep_size: 1536MB
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ .Release.Name }}
  externalClusters:
    - name: {{ .Release.Name }}
      plugin:
          name: barman-cloud.cloudnative-pg.io
          parameters:
            barmanObjectName: {{ .Release.Name }}
            serverName: {{ .Release.Name }}
  monitoring:
    enablePodMonitor: true