apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gitlab-zoekt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  {{- with .Values.statefulSetAnnotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gitlab-zoekt.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "gitlab-zoekt.fullname" . }}
  replicas: {{ .Values.replicas }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        {{- with (merge (.Values.statefulSet.podAnnotations | default dict) (.Values.podAnnotations | default dict)) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gitlab-zoekt.selectorLabels" . | nindent 8 }}
        {{- include "gitlab.commonLabels" . | nindent 8 }}
        {{- with (merge (.Values.statefulSet.podLabels | default dict) (.Values.podLabels | default dict)) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab-zoekt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      {{- $commonInitContainers := include "gitlab-zoekt.commonInitContainers" . }}
      {{- if $commonInitContainers }}
      initContainers:
        {{- $commonInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: zoekt-indexer
          securityContext:
            {{- toYaml (merge .Values.indexer.securityContext .Values.securityContext) | nindent 12 }}
          image: {{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default "latest" }}
          imagePullPolicy: {{ coalesce .Values.indexer.image.pullPolicy .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.indexer.listen.port }}
            name: indexer
          livenessProbe:
            httpGet:
              path: /indexer/health
              port: {{ .Values.indexer.listen.port }}
          readinessProbe:
            httpGet:
              path: /indexer/health
              port: {{ .Values.indexer.listen.port }}
          resources:
            {{- toYaml (merge .Values.indexer.resources .Values.resources) | nindent 12 }}
          volumeMounts:
          - name: zoekt-index
            mountPath: /data/index
          - name: internal-api-secret
            readOnly: true
            mountPath: /.gitlab_shell_secret
            subPath: .gitlab_shell_secret
          {{- if include "gitlab-zoekt.hasCertificates" . }}
          {{-   include "gitlab.certificates.volumeMount" . | nindent 10 }}
          {{- end }}
          {{- include "gitlab.extraVolumeMounts" . | nindent 10 }}
          env:
          - name: GITLAB_ZOEKT_MODE
            value: "indexer"
          {{- if .Values.indexer.googleCloudProfiler.enabled }}
          - name: GOOGLE_CLOUD_PROFILER_ENABLED
            value: "true"
          {{- end }}
          {{- range $envName, $envValue := .Values.indexer.environment }}
          - name: {{ $envName }}
            value: {{ $envValue | quote }}
          {{- end }}
          - name: GITLAB_URL
            value: {{ template "gitlab-zoekt.internalApi.gitlabUrl" . }}
          - name: SERVICE_URL
            value: {{ template "gitlab-zoekt.internalApi.serviceUrl" . }}
        - name: zoekt-webserver
          securityContext:
            {{- toYaml (merge .Values.webserver.securityContext .Values.securityContext) | nindent 12 }}
          image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag | default "latest" }}
          imagePullPolicy: {{ coalesce .Values.webserver.image.pullPolicy .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webserver.listen.port }}
              name: webserver
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.webserver.listen.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.webserver.listen.port }}
          resources:
            {{- toYaml (merge .Values.webserver.resources .Values.resources) | nindent 12 }}
          volumeMounts:
          - name: zoekt-index
            mountPath: /data/index
          - name: internal-api-secret
            readOnly: true
            mountPath: /.gitlab_shell_secret
            subPath: .gitlab_shell_secret
          {{- if include "gitlab-zoekt.hasCertificates" . }}
          {{-   include "gitlab.certificates.volumeMount" . | nindent 10 }}
          {{- end }}
          {{- include "gitlab.extraVolumeMounts" . | nindent 10 }}
          env:
          - name: GITLAB_ZOEKT_MODE
            value: "webserver"
          {{- if .Values.webserver.googleCloudProfiler.enabled }}
          - name: GOOGLE_CLOUD_PROFILER_ENABLED
            value: "true"
          {{- end }}
          {{- range $envName, $envValue := .Values.webserver.environment }}
          - name: {{ $envName }}
            value: {{ $envValue | quote }}
          {{- end }}
        - name: zoekt-internal-gateway
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: {{ include "gitlab-zoekt.gatewayImage" . }}
          imagePullPolicy: {{ coalesce .Values.gateway.image.pullPolicy .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gateway.listen.port }}
              name: gateway
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gateway.listen.port }}
              {{- if .Values.gateway.tls.certificate.enabled }}
              scheme: HTTPS
              {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gateway.listen.port }}
              {{- if .Values.gateway.tls.certificate.enabled }}
              scheme: HTTPS
              {{- end }}
          resources:
            {{- toYaml (merge .Values.gateway.resources .Values.resources) | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: internal-nginx-var-run
              mountPath: /var/run
            - name: internal-nginx-var-cache-nginx
              mountPath: /var/cache/nginx
            {{- if .Values.gateway.tls.certificate.enabled }}
            - name: gateway-cert
              mountPath: /etc/ssl/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: gateway-cert
              mountPath: /etc/ssl/tls.key
              subPath: tls.key
              readOnly: true
            {{- end }}
            {{- if include "gitlab-zoekt.hasCertificates" . }}
            {{-   include "gitlab.certificates.volumeMount" . | nindent 12 }}
            {{- end }}
            {{- include "gitlab.extraVolumeMounts" . | nindent 12 }}
        {{- include "gitlab.extraContainers" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "gitlab-zoekt.configZoektGatewayMapName" . }}
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: internal-nginx-var-run
          emptyDir: {}
        - name: internal-nginx-var-cache-nginx
          emptyDir: {}
        {{- if .Values.gateway.tls.certificate.enabled }}
        - name: gateway-cert
          secret:
            secretName: {{ .Values.gateway.tls.certificate.secretName }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- end }}
        - name: internal-api-secret
          secret:
            secretName: {{ template "gitlab-zoekt.internalApi.secretName" . }}
            items:
              - key: {{ template "gitlab-zoekt.internalApi.secretKey" . }}
                path: ".gitlab_shell_secret"
        {{- if include "gitlab-zoekt.hasCertificates" . }}
        {{-   include "gitlab.certificates.volumes" . | nindent 8 }}
        {{- end }}
        {{- include "gitlab.extraVolumes" . | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: zoekt-index
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName:  {{ .Values.indexStorageClassName }}
      resources:
        requests:
          storage: {{ .Values.indexStorage }}
